name: Cypress-cucumber Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
      - name: Generate reports
        if: always()
        run: npm run cypress:report
      - name: Upload artifact cucumber-report
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: cucumber-report
            path: ./reports/cucumber-htmlreport
            retention-days: 5 
      - name: Deploy to pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: reports/cucumber-htmlreport/  
